### ISSUE TITLE
Readme File

### ISSUE THREAD

**Issue by andupotorac** [muerrilla/stable-diffusion-Latentshop#3]
Would be great to have something to start with. :)

**Comment by muerrilla** [comment]
> Would be great to have something to start with. :)

Truer words have never been spoken but it's a hefty job (needs lots of explaining by examples) I've had not had enough time for yet, which is why I haven't properly released this thing yet, just uploaded it for the super-curious. 

Meanwhile you can check out the [discussion here](https://github.com/muerrilla/stable-diffusion-Latentshop/discussions/1#discussion-5273170) to get an idea of how it works. Also try the presets and see what they do, it might help.

I'm on vacation right now, but I hope I can do this when I get back.

**Comment by andupotorac** [comment]
Thanks, this will help! Enjoy your vacation. :)
